      
header:
  calibration_date: 2025-07-10
  frame_id: rs16_lidar
child_frame_id: chassis_camera
transform:
  translation:
    x: 0.055
    y: 0.025
    z: 0.065
  rotation: 
    x: -0.60918
    y: 0.638971
    z: -0.32881
    w: 0.335409

    