// Generated by gencpp from file piper_msgs/EnableResponse.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_MESSAGE_ENABLERESPONSE_H
#define PIPER_MSGS_MESSAGE_ENABLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piper_msgs
{
template <class ContainerAllocator>
struct EnableResponse_
{
  typedef EnableResponse_<ContainerAllocator> Type;

  EnableResponse_()
    : enable_response(false)  {
    }
  EnableResponse_(const ContainerAllocator& _alloc)
    : enable_response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_response_type;
  _enable_response_type enable_response;





  typedef boost::shared_ptr< ::piper_msgs::EnableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piper_msgs::EnableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EnableResponse_

typedef ::piper_msgs::EnableResponse_<std::allocator<void> > EnableResponse;

typedef boost::shared_ptr< ::piper_msgs::EnableResponse > EnableResponsePtr;
typedef boost::shared_ptr< ::piper_msgs::EnableResponse const> EnableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piper_msgs::EnableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piper_msgs::EnableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piper_msgs::EnableResponse_<ContainerAllocator1> & lhs, const ::piper_msgs::EnableResponse_<ContainerAllocator2> & rhs)
{
  return lhs.enable_response == rhs.enable_response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piper_msgs::EnableResponse_<ContainerAllocator1> & lhs, const ::piper_msgs::EnableResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piper_msgs::EnableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piper_msgs::EnableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs::EnableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs::EnableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs::EnableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs::EnableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piper_msgs::EnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1529042fb890f11f44ac64efb128c1d9";
  }

  static const char* value(const ::piper_msgs::EnableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1529042fb890f11fULL;
  static const uint64_t static_value2 = 0x44ac64efb128c1d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::piper_msgs::EnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piper_msgs/EnableResponse";
  }

  static const char* value(const ::piper_msgs::EnableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piper_msgs::EnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enable_response  # 响应消息类型为bool\n"
"\n"
;
  }

  static const char* value(const ::piper_msgs::EnableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piper_msgs::EnableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable_response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piper_msgs::EnableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piper_msgs::EnableResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "enable_response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIPER_MSGS_MESSAGE_ENABLERESPONSE_H
