// Generated by gencpp from file piper_msgs/EnableRequest.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_MESSAGE_ENABLEREQUEST_H
#define PIPER_MSGS_MESSAGE_ENABLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piper_msgs
{
template <class ContainerAllocator>
struct EnableRequest_
{
  typedef EnableRequest_<ContainerAllocator> Type;

  EnableRequest_()
    : enable_request(false)  {
    }
  EnableRequest_(const ContainerAllocator& _alloc)
    : enable_request(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_request_type;
  _enable_request_type enable_request;





  typedef boost::shared_ptr< ::piper_msgs::EnableRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piper_msgs::EnableRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EnableRequest_

typedef ::piper_msgs::EnableRequest_<std::allocator<void> > EnableRequest;

typedef boost::shared_ptr< ::piper_msgs::EnableRequest > EnableRequestPtr;
typedef boost::shared_ptr< ::piper_msgs::EnableRequest const> EnableRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piper_msgs::EnableRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piper_msgs::EnableRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piper_msgs::EnableRequest_<ContainerAllocator1> & lhs, const ::piper_msgs::EnableRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable_request == rhs.enable_request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piper_msgs::EnableRequest_<ContainerAllocator1> & lhs, const ::piper_msgs::EnableRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piper_msgs::EnableRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piper_msgs::EnableRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs::EnableRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs::EnableRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs::EnableRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs::EnableRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piper_msgs::EnableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4d2a33bd24e85ccd5f8fbef5fbeeb5f";
  }

  static const char* value(const ::piper_msgs::EnableRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4d2a33bd24e85ccULL;
  static const uint64_t static_value2 = 0xd5f8fbef5fbeeb5fULL;
};

template<class ContainerAllocator>
struct DataType< ::piper_msgs::EnableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piper_msgs/EnableRequest";
  }

  static const char* value(const ::piper_msgs::EnableRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piper_msgs::EnableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enable_request  # 请求消息类型为bool\n"
;
  }

  static const char* value(const ::piper_msgs::EnableRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piper_msgs::EnableRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable_request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piper_msgs::EnableRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piper_msgs::EnableRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "enable_request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIPER_MSGS_MESSAGE_ENABLEREQUEST_H
