// Generated by gencpp from file piper_msgs/GoZeroRequest.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_MESSAGE_GOZEROREQUEST_H
#define PIPER_MSGS_MESSAGE_GOZEROREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piper_msgs
{
template <class ContainerAllocator>
struct GoZeroRequest_
{
  typedef GoZeroRequest_<ContainerAllocator> Type;

  GoZeroRequest_()
    : is_mit_mode(false)  {
    }
  GoZeroRequest_(const ContainerAllocator& _alloc)
    : is_mit_mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_mit_mode_type;
  _is_mit_mode_type is_mit_mode;





  typedef boost::shared_ptr< ::piper_msgs::GoZeroRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piper_msgs::GoZeroRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoZeroRequest_

typedef ::piper_msgs::GoZeroRequest_<std::allocator<void> > GoZeroRequest;

typedef boost::shared_ptr< ::piper_msgs::GoZeroRequest > GoZeroRequestPtr;
typedef boost::shared_ptr< ::piper_msgs::GoZeroRequest const> GoZeroRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piper_msgs::GoZeroRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piper_msgs::GoZeroRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piper_msgs::GoZeroRequest_<ContainerAllocator1> & lhs, const ::piper_msgs::GoZeroRequest_<ContainerAllocator2> & rhs)
{
  return lhs.is_mit_mode == rhs.is_mit_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piper_msgs::GoZeroRequest_<ContainerAllocator1> & lhs, const ::piper_msgs::GoZeroRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piper_msgs::GoZeroRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piper_msgs::GoZeroRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs::GoZeroRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs::GoZeroRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs::GoZeroRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs::GoZeroRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piper_msgs::GoZeroRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30ebeb9eeb641141e70d6beb2a7c36ee";
  }

  static const char* value(const ::piper_msgs::GoZeroRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30ebeb9eeb641141ULL;
  static const uint64_t static_value2 = 0xe70d6beb2a7c36eeULL;
};

template<class ContainerAllocator>
struct DataType< ::piper_msgs::GoZeroRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piper_msgs/GoZeroRequest";
  }

  static const char* value(const ::piper_msgs::GoZeroRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piper_msgs::GoZeroRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_mit_mode\n"
;
  }

  static const char* value(const ::piper_msgs::GoZeroRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piper_msgs::GoZeroRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_mit_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoZeroRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piper_msgs::GoZeroRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piper_msgs::GoZeroRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "is_mit_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_mit_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIPER_MSGS_MESSAGE_GOZEROREQUEST_H
