// Generated by gencpp from file piper_msgs/GoZero.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_MESSAGE_GOZERO_H
#define PIPER_MSGS_MESSAGE_GOZERO_H

#include <ros/service_traits.h>


#include <piper_msgs/GoZeroRequest.h>
#include <piper_msgs/GoZeroResponse.h>


namespace piper_msgs
{

struct GoZero
{

typedef GoZeroRequest Request;
typedef GoZeroResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoZero
} // namespace piper_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::piper_msgs::GoZero > {
  static const char* value()
  {
    return "d8cded8be1d1727ecab27b0820b4be6f";
  }

  static const char* value(const ::piper_msgs::GoZero&) { return value(); }
};

template<>
struct DataType< ::piper_msgs::GoZero > {
  static const char* value()
  {
    return "piper_msgs/GoZero";
  }

  static const char* value(const ::piper_msgs::GoZero&) { return value(); }
};


// service_traits::MD5Sum< ::piper_msgs::GoZeroRequest> should match
// service_traits::MD5Sum< ::piper_msgs::GoZero >
template<>
struct MD5Sum< ::piper_msgs::GoZeroRequest>
{
  static const char* value()
  {
    return MD5Sum< ::piper_msgs::GoZero >::value();
  }
  static const char* value(const ::piper_msgs::GoZeroRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::piper_msgs::GoZeroRequest> should match
// service_traits::DataType< ::piper_msgs::GoZero >
template<>
struct DataType< ::piper_msgs::GoZeroRequest>
{
  static const char* value()
  {
    return DataType< ::piper_msgs::GoZero >::value();
  }
  static const char* value(const ::piper_msgs::GoZeroRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::piper_msgs::GoZeroResponse> should match
// service_traits::MD5Sum< ::piper_msgs::GoZero >
template<>
struct MD5Sum< ::piper_msgs::GoZeroResponse>
{
  static const char* value()
  {
    return MD5Sum< ::piper_msgs::GoZero >::value();
  }
  static const char* value(const ::piper_msgs::GoZeroResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::piper_msgs::GoZeroResponse> should match
// service_traits::DataType< ::piper_msgs::GoZero >
template<>
struct DataType< ::piper_msgs::GoZeroResponse>
{
  static const char* value()
  {
    return DataType< ::piper_msgs::GoZero >::value();
  }
  static const char* value(const ::piper_msgs::GoZeroResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIPER_MSGS_MESSAGE_GOZERO_H
