# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 3.142
    has_acceleration_limits: false
    max_acceleration: 0
    # Angle limits: ±154° = ±2.687 rad
    has_position_limits: true
    max_position: 2.687
    min_position: -2.687
  joint2:
    has_velocity_limits: true
    max_velocity: 3.403
    has_acceleration_limits: false
    max_acceleration: 0
    # Angle limits: 0°~195° = 0~3.403 rad
    has_position_limits: true
    max_position: 3.403
    min_position: 0.0
  joint3:
    has_velocity_limits: true
    max_velocity: 3.142
    has_acceleration_limits: false
    max_acceleration: 0
    # Angle limits: -175°~0° = -3.054~0 rad
    has_position_limits: true
    max_position: 0.0
    min_position: -3.054
  joint4:
    has_velocity_limits: true
    max_velocity: 3.927
    has_acceleration_limits: false
    max_acceleration: 0
    # Angle limits: -102°~102° = -1.780~1.780 rad
    has_position_limits: true
    max_position: 1.780
    min_position: -1.780
  joint5:
    has_velocity_limits: true
    max_velocity: 3.927
    has_acceleration_limits: false
    max_acceleration: 0
    # Angle limits: -75°~75° = -1.309~1.309 rad
    has_position_limits: true
    max_position: 1.309
    min_position: -1.309
  joint6:
    has_velocity_limits: true
    max_velocity: 3.927
    has_acceleration_limits: false
    max_acceleration: 0
    # Angle limits: ±120° = ±2.094 rad
    has_position_limits: true
    max_position: 2.094
    min_position: -2.094