// Generated by gencpp from file piper_msgs/Enable.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_MESSAGE_ENABLE_H
#define PIPER_MSGS_MESSAGE_ENABLE_H

#include <ros/service_traits.h>


#include <piper_msgs/EnableRequest.h>
#include <piper_msgs/EnableResponse.h>


namespace piper_msgs
{

struct Enable
{

typedef EnableRequest Request;
typedef EnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Enable
} // namespace piper_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::piper_msgs::Enable > {
  static const char* value()
  {
    return "ab5da25e2334681fe9da4d5fb9858409";
  }

  static const char* value(const ::piper_msgs::Enable&) { return value(); }
};

template<>
struct DataType< ::piper_msgs::Enable > {
  static const char* value()
  {
    return "piper_msgs/Enable";
  }

  static const char* value(const ::piper_msgs::Enable&) { return value(); }
};


// service_traits::MD5Sum< ::piper_msgs::EnableRequest> should match
// service_traits::MD5Sum< ::piper_msgs::Enable >
template<>
struct MD5Sum< ::piper_msgs::EnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::piper_msgs::Enable >::value();
  }
  static const char* value(const ::piper_msgs::EnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::piper_msgs::EnableRequest> should match
// service_traits::DataType< ::piper_msgs::Enable >
template<>
struct DataType< ::piper_msgs::EnableRequest>
{
  static const char* value()
  {
    return DataType< ::piper_msgs::Enable >::value();
  }
  static const char* value(const ::piper_msgs::EnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::piper_msgs::EnableResponse> should match
// service_traits::MD5Sum< ::piper_msgs::Enable >
template<>
struct MD5Sum< ::piper_msgs::EnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::piper_msgs::Enable >::value();
  }
  static const char* value(const ::piper_msgs::EnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::piper_msgs::EnableResponse> should match
// service_traits::DataType< ::piper_msgs::Enable >
template<>
struct DataType< ::piper_msgs::EnableResponse>
{
  static const char* value()
  {
    return DataType< ::piper_msgs::Enable >::value();
  }
  static const char* value(const ::piper_msgs::EnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIPER_MSGS_MESSAGE_ENABLE_H
