// Generated by gencpp from file piper_msgs/GoZeroResponse.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_MESSAGE_GOZERORESPONSE_H
#define PIPER_MSGS_MESSAGE_GOZERORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piper_msgs
{
template <class ContainerAllocator>
struct GoZeroResponse_
{
  typedef GoZeroResponse_<ContainerAllocator> Type;

  GoZeroResponse_()
    : code(0)
    , status(false)  {
    }
  GoZeroResponse_(const ContainerAllocator& _alloc)
    : code(0)
    , status(false)  {
  (void)_alloc;
    }



   typedef int64_t _code_type;
  _code_type code;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::piper_msgs::GoZeroResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piper_msgs::GoZeroResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoZeroResponse_

typedef ::piper_msgs::GoZeroResponse_<std::allocator<void> > GoZeroResponse;

typedef boost::shared_ptr< ::piper_msgs::GoZeroResponse > GoZeroResponsePtr;
typedef boost::shared_ptr< ::piper_msgs::GoZeroResponse const> GoZeroResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piper_msgs::GoZeroResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piper_msgs::GoZeroResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piper_msgs::GoZeroResponse_<ContainerAllocator1> & lhs, const ::piper_msgs::GoZeroResponse_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piper_msgs::GoZeroResponse_<ContainerAllocator1> & lhs, const ::piper_msgs::GoZeroResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piper_msgs::GoZeroResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piper_msgs::GoZeroResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs::GoZeroResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs::GoZeroResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs::GoZeroResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs::GoZeroResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piper_msgs::GoZeroResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34441fad838c25a9993eed8255bd6e41";
  }

  static const char* value(const ::piper_msgs::GoZeroResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34441fad838c25a9ULL;
  static const uint64_t static_value2 = 0x993eed8255bd6e41ULL;
};

template<class ContainerAllocator>
struct DataType< ::piper_msgs::GoZeroResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piper_msgs/GoZeroResponse";
  }

  static const char* value(const ::piper_msgs::GoZeroResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piper_msgs::GoZeroResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 code\n"
"bool status  # 响应消息类型为bool\n"
;
  }

  static const char* value(const ::piper_msgs::GoZeroResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piper_msgs::GoZeroResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoZeroResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piper_msgs::GoZeroResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piper_msgs::GoZeroResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "code: ";
    Printer<int64_t>::stream(s, indent + "  ", v.code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIPER_MSGS_MESSAGE_GOZERORESPONSE_H
