// Generated by gencpp from file piper_msgs/Gripper.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_MESSAGE_GRIPPER_H
#define PIPER_MSGS_MESSAGE_GRIPPER_H

#include <ros/service_traits.h>


#include <piper_msgs/GripperRequest.h>
#include <piper_msgs/GripperResponse.h>


namespace piper_msgs
{

struct Gripper
{

typedef GripperRequest Request;
typedef GripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Gripper
} // namespace piper_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::piper_msgs::Gripper > {
  static const char* value()
  {
    return "fca0ae84ccaed9dee57e974f132f6119";
  }

  static const char* value(const ::piper_msgs::Gripper&) { return value(); }
};

template<>
struct DataType< ::piper_msgs::Gripper > {
  static const char* value()
  {
    return "piper_msgs/Gripper";
  }

  static const char* value(const ::piper_msgs::Gripper&) { return value(); }
};


// service_traits::MD5Sum< ::piper_msgs::GripperRequest> should match
// service_traits::MD5Sum< ::piper_msgs::Gripper >
template<>
struct MD5Sum< ::piper_msgs::GripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::piper_msgs::Gripper >::value();
  }
  static const char* value(const ::piper_msgs::GripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::piper_msgs::GripperRequest> should match
// service_traits::DataType< ::piper_msgs::Gripper >
template<>
struct DataType< ::piper_msgs::GripperRequest>
{
  static const char* value()
  {
    return DataType< ::piper_msgs::Gripper >::value();
  }
  static const char* value(const ::piper_msgs::GripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::piper_msgs::GripperResponse> should match
// service_traits::MD5Sum< ::piper_msgs::Gripper >
template<>
struct MD5Sum< ::piper_msgs::GripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::piper_msgs::Gripper >::value();
  }
  static const char* value(const ::piper_msgs::GripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::piper_msgs::GripperResponse> should match
// service_traits::DataType< ::piper_msgs::Gripper >
template<>
struct DataType< ::piper_msgs::GripperResponse>
{
  static const char* value()
  {
    return DataType< ::piper_msgs::Gripper >::value();
  }
  static const char* value(const ::piper_msgs::GripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIPER_MSGS_MESSAGE_GRIPPER_H
