fake_interpolating_controller_rate: 100
controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - arm_joint6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint7
      - arm_joint8
initial:  # Define initial robot poses per group
  - group: arm
    pose: zero
  - group: gripper
    pose: close