# Kinematics configuration for mobile_manipulator2
# piper组：仅6轴机械臂（joint1-6）
piper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.15

# piper_with_gripper组：包含所有8个关节（6轴+2夹爪）
# 注意：由于包含固定关节，此组可能无法使用KDL求解器进行IK
piper_with_gripper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.15

# gripper组：夹爪控制（joint7-8）
# 夹爪通常不需要IK求解，直接控制关节即可