piper:
  # piper是纯链式结构（joint1-6），可以使用KDL求解器
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.15

# arm组包含所有8个关节，用于轨迹执行
# gripper组包含joint7-8，用于夹爪控制
# 这两个组不需要运动学求解器配置