// Generated by gencpp from file moveit_ctrl/JointMoveitCtrl.msg
// DO NOT EDIT!


#ifndef MOVEIT_CTRL_MESSAGE_JOINTMOVEITCTRL_H
#define MOVEIT_CTRL_MESSAGE_JOINTMOVEITCTRL_H

#include <ros/service_traits.h>


#include <moveit_ctrl/JointMoveitCtrlRequest.h>
#include <moveit_ctrl/JointMoveitCtrlResponse.h>


namespace moveit_ctrl
{

struct JointMoveitCtrl
{

typedef JointMoveitCtrlRequest Request;
typedef JointMoveitCtrlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointMoveitCtrl
} // namespace moveit_ctrl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_ctrl::JointMoveitCtrl > {
  static const char* value()
  {
    return "51cb988f5ae355fbe239bcbc18431f99";
  }

  static const char* value(const ::moveit_ctrl::JointMoveitCtrl&) { return value(); }
};

template<>
struct DataType< ::moveit_ctrl::JointMoveitCtrl > {
  static const char* value()
  {
    return "moveit_ctrl/JointMoveitCtrl";
  }

  static const char* value(const ::moveit_ctrl::JointMoveitCtrl&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_ctrl::JointMoveitCtrlRequest> should match
// service_traits::MD5Sum< ::moveit_ctrl::JointMoveitCtrl >
template<>
struct MD5Sum< ::moveit_ctrl::JointMoveitCtrlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_ctrl::JointMoveitCtrl >::value();
  }
  static const char* value(const ::moveit_ctrl::JointMoveitCtrlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_ctrl::JointMoveitCtrlRequest> should match
// service_traits::DataType< ::moveit_ctrl::JointMoveitCtrl >
template<>
struct DataType< ::moveit_ctrl::JointMoveitCtrlRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_ctrl::JointMoveitCtrl >::value();
  }
  static const char* value(const ::moveit_ctrl::JointMoveitCtrlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_ctrl::JointMoveitCtrlResponse> should match
// service_traits::MD5Sum< ::moveit_ctrl::JointMoveitCtrl >
template<>
struct MD5Sum< ::moveit_ctrl::JointMoveitCtrlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_ctrl::JointMoveitCtrl >::value();
  }
  static const char* value(const ::moveit_ctrl::JointMoveitCtrlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_ctrl::JointMoveitCtrlResponse> should match
// service_traits::DataType< ::moveit_ctrl::JointMoveitCtrl >
template<>
struct DataType< ::moveit_ctrl::JointMoveitCtrlResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_ctrl::JointMoveitCtrl >::value();
  }
  static const char* value(const ::moveit_ctrl::JointMoveitCtrlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_CTRL_MESSAGE_JOINTMOVEITCTRL_H
