(cl:defpackage moveit_ctrl-srv
  (:use )
  (:export
   "JOINTMOVEITCTRL"
   "<JOINTMOVEITCTRL-REQUEST>"
   "JOINTMOVEITCTRL-REQUEST"
   "<JOINTMOVEITCTRL-RESPONSE>"
   "JOINTMOVEITCTRL-RESPONSE"
  ))

