topics:
  outputs:
    image_raw:
      name: /camera/hand/color/image_raw
      type: sensor_msgs/Image
    hand_image:
      name: /camera/hand/color/image_raw
      type: sensor_msgs/Image
    top_image:
      name: /camera/top/color/image_raw
      type: sensor_msgs/Image