topics:
  outputs:
    top_camera:
      color_raw:
        name: /camera/top/color/raw
        type: sensor_msgs/Image
      depth_raw:
        name: /camera/top/depth/raw
        type: sensor_msgs/Image
    hand_camera:
      color_raw:
        name: /camera/top/color/raw
        type: sensor_msgs/Image
      depth_raw:
        name: /camera/top/depth/raw
        type: sensor_msgs/Image
    chassis_camera:
      color_raw:
        name: /camera/top/color/raw
        type: sensor_msgs/Image
      depth_raw:
        name: /camera/top/depth/raw
        type: sensor_msgs/Image